import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from "next/font/google";
import ThemeProvider from "./ThemeProvider";
import CartProvider from "@/components/Cart/CartProvider";
import CartDrawer from "@/components/Cart/CartDrawer";

const roboto = Roboto({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} bg-(--background) text-(--text-colour) min-h-screen flex flex-col`}
      >
        <ThemeProvider>
          <CartProvider>
            {children}

            <CartDrawer />
          </CartProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
