import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from "next/font/google";
import ThemeProvider from "./ThemeProvider";
import CartProvider from "@/components/Cart/CartProvider";
import CartDrawer from "@/components/Cart/CartDrawer";
import Header from "@/components/Header/Header";
import SessionProvide from "./SessionProvider";

const roboto = Roboto({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} mb-6 bg-(--background) text-(--text-colour) min-h-screen flex flex-col`}
      >
        <SessionProvide>
          <ThemeProvider>
            <CartProvider>
              <Header />
              {children}

              <CartDrawer />
            </CartProvider>
          </ThemeProvider>
        </SessionProvide>
      </body>
    </html>
  );
}
